"""Translates mpv / libplacebo user shaders into Direct3D 11 HLSL passes.

Each pass of a user shader becomes a complete GLSL 450 shader: the pass body,
with the macros libplacebo defines around it (NAME_tex, NAME_texOff, NAME_pos,
NAME_gather, ...). glslang compiles it to SPIR-V and SPIRV-Cross turns that into
HLSL shader model 5 -- the route libplacebo itself takes on Direct3D 11 -- so
matrix order, gathers and integer arithmetic keep their GLSL meaning exactly.

Compute passes written for workgroup-shared memory (ArtCNN keeps its 3x3
neighbourhood in a `shared` array filled once per workgroup) have no HLSL
equivalent. They are rewritten to fetch the neighbourhood per invocation: the
same texels, the same weights, only the caching goes.

Two uses:

    python mpv_shaders.py <shader> <output dir> [--tools <dir>]

        One shader into HLSL passes and a manifest listing what each pass binds
        and how big its output is, for the DLSS 5 harness
        (tools/dlssnr_probe/mpvhook.inl), which compiles them when it runs.

    python mpv_shaders.py renderer [--upstream <dir>] [--tools <dir>]

        The prescalers the renderer embeds (FSRCNNX 8 and 16, RAVU-zoom and
        ArtCNN C4F16 DS): their
        passes under Shaders/mpv/<shader>/, lookup tables as half floats next to
        them, the tables in Source/Upscale/MpvShaderTables.h, and the generated
        blocks of Shaders/compile_shaders.cmd and Source/res/MpcVideoRenderer.rc2.
        Build the Shaders project again afterwards (compile_shaders.cmd), since the
        passes are not items of it.

--upstream is where the user shaders are (tools/dlssnr_probe/upscalers by
default), --tools where glslang and spirv-cross are (its tools folder).
"""

import os
import re
import subprocess
import sys

MAX_BINDS = 8
MAX_PARAMS = 8

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, "..", ".."))

# The prescalers in the renderer: file, C++ name, name the renderer shows.
RENDERER_SHADERS = [
    ("FSRCNNX_x2_8-0-4-1.glsl", "FSRCNNX8", "FSRCNNX 8"),
    ("FSRCNNX_x2_16-0-4-1.glsl", "FSRCNNX16", "FSRCNNX 16"),
    ("ravu-zoom-ar-r3.hook", "RavuZoomAR3", "RAVU-zoom"),
    ("ArtCNN_C4F16_DS.glsl", "ArtCNNC4F16DS", "ArtCNN C4F16 DS"),
]
FIRST_RESOURCE_ID = 2000

CMD_BEGIN = "REM mpv prescalers: generated by mpv\\mpv_shaders.py, do not edit this block"
CMD_END = "REM end of the mpv prescalers"
RC_BEGIN = "// mpv prescalers: generated by Shaders/mpv/mpv_shaders.py, do not edit this block"
RC_END = "// end of the mpv prescalers"


def parse(text):
    """Splits a user shader into passes, textures and parameters."""
    sections = []
    directives, code = [], []

    def close():
        if directives:
            sections.append((list(directives), list(code)))

    for line in text.splitlines():
        if line.startswith("//!"):
            if code and any(c.strip() for c in code):
                close()
                directives.clear()
                code.clear()
            directives.append(line[3:].strip())
        elif directives:
            code.append(line)
    close()

    passes, textures, params = [], [], []
    for dirs, body in sections:
        keys = [d.split(None, 1) for d in dirs]
        first = keys[0][0].upper()
        if first == "TEXTURE":
            tex = {"name": keys[0][1], "filter": "LINEAR", "border": "CLAMP", "format": "rgba8"}
            for k in keys[1:]:
                key = k[0].upper()
                if key == "SIZE":
                    tex["size"] = [int(v) for v in k[1].split()]
                elif key == "FORMAT":
                    tex["format"] = k[1].strip()
                elif key == "FILTER":
                    tex["filter"] = k[1].strip().upper()
                elif key == "BORDER":
                    tex["border"] = k[1].strip().upper()
            tex["data"] = "".join(l.strip() for l in body)
            textures.append(tex)
        elif first == "PARAM":
            par = {"name": keys[0][1], "type": "float"}
            for k in keys[1:]:
                if k[0].upper() == "TYPE":
                    par["type"] = k[1].strip()
            values = [l.strip() for l in body if l.strip()]
            par["value"] = float(values[0]) if values else 0.0
            params.append(par)
        else:
            p = {"hooks": [], "binds": [], "save": None, "width": None, "height": None,
                 "when": None, "offset": None, "components": 4, "desc": "", "compute": None}
            for k in keys:
                key = k[0].upper()
                arg = k[1].strip() if len(k) > 1 else ""
                if key == "HOOK":
                    p["hooks"].append(arg)
                elif key == "BIND":
                    p["binds"].append(arg)
                elif key == "SAVE":
                    p["save"] = arg
                elif key == "WIDTH":
                    p["width"] = arg
                elif key == "HEIGHT":
                    p["height"] = arg
                elif key == "WHEN":
                    p["when"] = arg
                elif key == "OFFSET":
                    p["offset"] = arg
                elif key == "COMPONENTS":
                    p["components"] = int(arg)
                elif key == "DESC":
                    p["desc"] = arg
                elif key == "COMPUTE":
                    p["compute"] = [int(v) for v in arg.split()]
                else:
                    raise ValueError("unsupported directive //!" + key)
            p["code"] = "\n".join(body)
            passes.append(p)
    return passes, textures, params


def unshare(code):
    """Rewrites a compute pass that caches its neighbourhood in a `shared` array."""
    m = re.search(r"shared\s+(\w+)\s+inp\[(\d+)\]\[isize\.y\]\[isize\.x\];", code)
    if not m:
        return code
    kind, channels = m.group(1), int(m.group(2))
    scale = re.search(r"const ivec2 input_base = \(base \+ ivec2\(x,y\) - offset\) \* ivec2\((\d+), (\d+)\);", code)
    fills = dict(re.findall(r"inp\[(\d+)\]\[y\]\[x\] = (.+);", code))
    if not scale or len(fills) != channels:
        raise ValueError("unexpected shared-memory layout")

    def clamped(expr):
        # texelFetch(NAME_raw, E, 0) -> the same texel, clamped inside the texture
        return re.sub(r"texelFetch\((\w+)_raw, (input_base \+ ivec2\(\d+, \d+\)), 0\)",
                      lambda t: "texelFetch({0}_raw, clamp({1}, ivec2(0), ivec2({0}_size) - ivec2(1)), 0)".format(t.group(1), t.group(2)),
                      expr)

    helpers = []
    for c in range(channels):
        helpers.append(
            "{kind} inp_fetch_{c}(ivec2 d) {{\n"
            "    const ivec2 input_base = (ivec2(gl_GlobalInvocationID.xy) + d - offset) * ivec2({sx}, {sy});\n"
            "    return {expr};\n"
            "}}".format(kind=kind, c=c, sx=scale.group(1), sy=scale.group(2), expr=clamped(fills[str(c)])))

    code = code.replace(m.group(0), "")
    # The fill loops, up to the barrier.
    code = re.sub(r"    for \(uint y = local_xy\.y;.*?barrier\(\);\n", "", code, flags=re.S)
    code = re.sub(r"inp\[(\d+)\]\[local_xy\.y \+ (\d+)\]\[local_xy\.x \+ (\d+)\]",
                  lambda t: "inp_fetch_{}(ivec2({}, {}))".format(t.group(1), t.group(3), t.group(2)), code)
    return code.replace("void hook() {", "\n".join(helpers) + "\nvoid hook() {", 1)


def glsl_for(p, params, textures):
    """The complete GLSL 450 shader of one pass."""
    compute = p["compute"] is not None
    binds = p["binds"]
    if len(binds) > MAX_BINDS:
        raise ValueError("too many binds")
    lut_names = {t["name"] for t in textures}

    out = ["#version 450"]
    if compute:
        bw, bh = p["compute"][0], p["compute"][1]
        tw, th = (p["compute"][2], p["compute"][3]) if len(p["compute"]) >= 4 else (bw, bh)
        out.append("layout(local_size_x = {}, local_size_y = {}) in;".format(tw, th))
        out.append("layout(rgba16f, binding = 0) writeonly uniform image2D out_image;")
    else:
        out.append("layout(location = 0) in vec2 pl_pos;")
        out.append("layout(location = 0) out vec4 pl_out;")
    out.append("layout(std140, binding = 0) uniform MpvGlobals {")
    out.append("    vec4 pl_out_size;                    // w, h, 1/w, 1/h")
    out.append("    vec4 pl_input_target;                // input_size, target_size")
    out.append("    vec4 pl_misc;                        // tex_offset, random, frame")
    out.append("    vec4 pl_tex_size[{}];                 // w, h, 1/w, 1/h".format(MAX_BINDS))
    out.append("    vec4 pl_tex_shift[{}];                // position shift, normalized".format(MAX_BINDS))
    out.append("    vec4 pl_params[{}];".format(MAX_PARAMS))
    out.append("};")
    out.append("#define input_size (pl_input_target.xy)")
    out.append("#define target_size (pl_input_target.zw)")
    out.append("#define tex_offset (pl_misc.xy)")
    out.append("#define random (pl_misc.z)")
    out.append("#define frame (int(pl_misc.w))")
    for i, par in enumerate(params):
        cast = "int" if par["type"].startswith("int") else ("uint" if par["type"].startswith("uint") else "float")
        out.append("#define {} ({}(pl_params[{}].x))".format(par["name"], cast, i))

    # HOOKED is also reachable under the hooked plane's own name (KrigBilateral reads
    # CHROMA_pt with only HOOKED bound), and a //!TEXTURE under its bare name.
    names = []
    for i, name in enumerate(binds):
        names.append((i, name))
        if name == "HOOKED":
            for hook in p["hooks"]:
                if hook not in binds:
                    names.append((i, hook))
    declared = set()
    for i, name in names:
        slot = i + 1
        if i not in declared:
            out.append("layout(binding = {}) uniform sampler2D {}_raw;".format(slot, binds[i]))
            declared.add(i)
        if name != binds[i]:
            out.append("#define {}_raw {}_raw".format(name, binds[i]))
        if name in lut_names:
            out.append("#define {0} {0}_raw".format(name))
        pos = ("{0}_map(gl_GlobalInvocationID.xy)".format(name) if compute
               else "(pl_pos + pl_tex_shift[{}].xy)".format(i))
        for line in (
            "#define {0}_size (pl_tex_size[{1}].xy)",
            "#define {0}_pt (pl_tex_size[{1}].zw)",
            "#define {0}_map(id) ((vec2(id) + vec2(0.5)) * pl_out_size.zw + pl_tex_shift[{1}].xy)",
            "#define {0}_pos " + pos,
            "#define {0}_rot (mat2(1.0, 0.0, 0.0, 1.0))",
            "#define {0}_off (vec2(0.0))",
            "#define {0}_mul (1.0)",
            "#define {0}_tex(pos) ({0}_mul * vec4(textureLod({0}_raw, pos, 0.0)))",
            "#define {0}_texOff(off) {0}_tex({0}_pos + {0}_pt * vec2(off))",
            "#define {0}_gather(pos, c) ({0}_mul * vec4(textureGather({0}_raw, pos, c)))",
        ):
            out.append(line.format(name, i))

    code = p["code"]
    # Full precision: glslang predefines the float16 extension's name whether or not
    # it is enabled, so the shaders' #ifdef would pick float16_t without it.
    code = re.sub(r"^\s*#extension GL_EXT_shader_explicit_arithmetic_types_float16\s*:\s*enable\s*$", "", code, flags=re.M)
    code = re.sub(r"^#ifdef GL_EXT_shader_explicit_arithmetic_types_float16\s*$", "#if 0", code, flags=re.M)
    if compute:
        code = unshare(code)
    out.append(code)
    out.append("void main() {")
    out.append("    hook();" if compute else "    pl_out = hook();")
    out.append("}")
    return "\n".join(out) + "\n"


def run(cmd):
    r = subprocess.run(cmd, capture_output=True, text=True)
    if r.returncode != 0:
        raise RuntimeError("{} failed:\n{}{}".format(os.path.basename(cmd[0]), r.stdout, r.stderr))
    return r.stdout


def tool_paths(tools):
    return (os.path.join(tools, "glslang", "bin", "glslang.exe"),
            os.path.join(tools, "bin", "spirv-cross.exe"))


def translate_pass(p, params, textures, outdir, base, tools):
    """GLSL of a pass through glslang and SPIRV-Cross; returns the HLSL text."""
    glslang, spirv_cross = tool_paths(tools)
    stage = "comp" if p["compute"] else "frag"
    glsl_path = os.path.join(outdir, base + "." + stage)
    spv_path = os.path.join(outdir, base + ".spv")
    hlsl_path = os.path.join(outdir, base + ".hlsl")
    open(glsl_path, "w", encoding="utf-8").write(glsl_for(p, params, textures))
    try:
        run([glslang, "-V", "--target-env", "vulkan1.1", "-S", stage, "-o", spv_path, glsl_path])
        run([spirv_cross, "--hlsl", "--shader-model", "50", "--output", hlsl_path, spv_path])
    finally:
        if os.path.exists(spv_path):
            os.remove(spv_path)
    return glsl_path, hlsl_path


def translate(src, outdir, tools):
    """One shader for the harness: HLSL passes and manifest.txt."""
    os.makedirs(outdir, exist_ok=True)
    passes, textures, params = parse(open(src, encoding="utf-8").read())
    if len(params) > MAX_PARAMS:
        raise ValueError("too many parameters")

    manifest = ["shader " + os.path.basename(src)]
    for par in params:
        manifest.append("param {} {!r}".format(par["name"], par["value"]))
    for t in textures:
        data = bytes.fromhex(t["data"])
        binfile = "texture_{}.bin".format(t["name"])
        open(os.path.join(outdir, binfile), "wb").write(data)
        size = t["size"] + [1] * (2 - len(t["size"]))
        manifest.append("texture {} {} {} {} {} {} {}".format(t["name"], size[0], size[1], t["format"], t["filter"], t["border"], binfile))

    for n, p in enumerate(passes):
        base = "pass{:02d}".format(n)
        translate_pass(p, params, textures, outdir, base, tools)
        manifest.append("pass " + base)
        manifest.append("desc " + p["desc"])
        manifest.append("hooks " + " ".join(p["hooks"]))
        manifest.append("binds " + " ".join(p["binds"]))
        manifest.append("save " + (p["save"] or "-"))
        manifest.append("width " + (p["width"] or "-"))
        manifest.append("height " + (p["height"] or "-"))
        manifest.append("when " + (p["when"] or "-"))
        manifest.append("offset " + (p["offset"] or "-"))
        manifest.append("components {}".format(p["components"]))
        manifest.append("compute " + (" ".join(str(v) for v in p["compute"]) if p["compute"] else "-"))
        manifest.append("hlsl " + base + ".hlsl")
        manifest.append("end")
        print("  {}  {:<8} {}".format(base, "compute" if p["compute"] else "pixel", p["desc"]))

    open(os.path.join(outdir, "manifest.txt"), "w", encoding="utf-8").write("\n".join(manifest) + "\n")
    print("{}: {} passes, {} textures, {} parameters -> {}".format(os.path.basename(src), len(passes), len(textures), len(params), outdir))


def licence_header(text):
    """The comment block a user shader opens with: its copyright and licence."""
    lines = []
    for line in text.splitlines():
        if line.startswith("//!") or not line.startswith("//"):
            break
        lines.append(line.rstrip())
    while lines and lines[-1].strip() in ("//", ""):
        lines.pop()
    return lines


def cstr(s):
    return "nullptr" if s is None else '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def replace_block(path, begin, end, block, anchor):
    """Puts block between the begin and end markers, or before anchor the first time."""
    text = open(path, encoding="utf-8").read()
    newline = "\r\n" if "\r\n" in text else "\n"
    text = text.replace("\r\n", "\n")
    body = "\n".join([begin] + block + [end]) + "\n"
    if begin in text:
        start = text.index(begin)
        stop = text.index(end, start) + len(end) + 1
        text = text[:start] + body + text[stop:]
    else:
        # After the newline an anchor opens with, so the block starts a line.
        at = text.index(anchor) + (1 if anchor.startswith("\n") else 0)
        text = text[:at] + body + "\n" + text[at:]
    open(path, "w", encoding="utf-8", newline="").write(text.replace("\n", newline))


def renderer(upstream, tools):
    """The prescalers the renderer embeds: HLSL, tables, compile lines and resources."""
    import numpy as np

    table = [
        "// Generated by Shaders/mpv/mpv_shaders.py from mpv user shaders: do not edit.",
        "//",
        "// The passes are compiled from Shaders/mpv/<shader>/passNN.hlsl by",
        "// Shaders/compile_shaders.cmd and embedded as FILE resources, with the lookup",
        "// tables, from the numbers below.",
        "//",
        "// FSRCNNX: Copyright (C) 2017-2021 igv (github.com/igv/FSRCNN-TensorFlow).",
        "// RAVU: Bin Jin (github.com/bjin/mpv-prescalers).",
        "// Both under the GNU Lesser General Public License 3.0 or later: see",
        "// Shaders/mpv/LICENSE.LGPL-3.0.txt.",
        "//",
        "// ArtCNN: Copyright (c) 2024 Joao Chrisostomo (github.com/Artoriuz/ArtCNN),",
        "// MIT licence: see Shaders/mpv/LICENSE.MIT.txt.",
        "",
        "#pragma once",
        "",
        '#include "MpvShader.h"',
        "",
    ]
    cmd = ["SET fxc_ps5=%fxcexe% /nologo /O2 /T ps_5_0",
           "SET fxc_cs5=%fxcexe% /nologo /O2 /T cs_5_0", ""]
    rc = []
    files = []
    resid = FIRST_RESOURCE_ID

    for name, symbol, shown in RENDERER_SHADERS:
        src = os.path.join(upstream, name)
        text = open(src, encoding="utf-8").read()
        passes, textures, params = parse(text)
        stem = os.path.splitext(name)[0]
        outdir = os.path.join(HERE, stem)
        os.makedirs(outdir, exist_ok=True)
        for old in os.listdir(outdir):
            if old.endswith((".hlsl", ".frag", ".bin")):
                os.remove(os.path.join(outdir, old))

        if params:
            raise ValueError(name + ": parameters are not supported in the renderer")
        header = licence_header(text)
        pass_rows = []
        for n, p in enumerate(passes):
            if p["hooks"] != ["LUMA"] or p["offset"] not in (None, "ALIGN"):
                raise ValueError("{}: pass {} is not a LUMA pass the renderer runs".format(name, n))
            base = "pass{:02d}".format(n)
            glsl_path, hlsl_path = translate_pass(p, params, textures, outdir, base, tools)
            os.remove(glsl_path)
            hlsl = open(hlsl_path, encoding="utf-8").read()
            intro = header + [
                "//",
                "// Pass {} of {} ({}), translated to HLSL by Shaders/mpv/mpv_shaders.py".format(n, name, p["desc"]),
                "// (glslang, then SPIRV-Cross): do not edit.",
                "",
            ]
            open(hlsl_path, "w", encoding="utf-8", newline="\n").write("\n".join(intro) + "\n" + hlsl)

            cso = "mpv_{}_{}.cso".format(stem, base)
            cmd.append('%{}% /Fo "%workdir%\\{}" "mpv\\{}\\{}.hlsl"'.format(
                "fxc_cs5" if p["compute"] else "fxc_ps5", cso, stem, base))
            rc.append('{:<31} FILE                    "..\\\\_bin\\\\shaders\\\\{}"'.format(resid, cso))
            files.append((resid, "_bin\\\\shaders\\\\" + cso))
            block = p["compute"][:2] if p["compute"] else [0, 0]
            pass_rows.append("\t{{ {}, {}, {}, {}, {}, {}, {}, {}, {}, {} }},".format(
                cstr(p["desc"]), cstr(" ".join(p["hooks"])), cstr(" ".join(p["binds"])), cstr(p["save"]),
                cstr(p["width"]), cstr(p["height"]), cstr(p["when"]), resid, block[0], block[1]))
            resid += 1

        texture_rows = []
        for t in textures:
            if t["format"] != "rgba16f" or len(t.get("size", [])) != 2:
                raise ValueError("{}: texture {} is not a 2D rgba16f table".format(name, t["name"]))
            w, h = t["size"]
            values = np.frombuffer(bytes.fromhex(t["data"]), dtype=np.float32)
            if values.size != 4 * w * h:
                raise ValueError("{}: texture {} has {} values for {}x{}".format(name, t["name"], values.size, w, h))
            binfile = t["name"] + ".bin"
            open(os.path.join(outdir, binfile), "wb").write(values.astype(np.float16).tobytes())
            rc.append('{:<31} FILE                    "..\\\\Shaders\\\\mpv\\\\{}\\\\{}"'.format(resid, stem, binfile))
            files.append((resid, "Shaders\\\\mpv\\\\{}\\\\{}".format(stem, binfile)))
            texture_rows.append("\t{{ {}, {}, {}, {}, {} }},".format(
                cstr(t["name"]), w, h, "true" if t["filter"] == "LINEAR" else "false", resid))
            resid += 1

        table.append("// {}: {} passes".format(name, len(passes)))
        table.append("static const MpvPassInfo kMpv{}Passes[] = {{".format(symbol))
        table += pass_rows
        table.append("};")
        if texture_rows:
            table.append("static const MpvTextureInfo kMpv{}Textures[] = {{".format(symbol))
            table += texture_rows
            table.append("};")
        table.append("static const MpvShaderInfo kMpv{0} = {{ L\"{1}\", kMpv{0}Passes, {2}, {3}, {4} }};".format(
            symbol, shown, len(passes), "kMpv{}Textures".format(symbol) if texture_rows else "nullptr", len(texture_rows)))
        table.append("")
        cmd.append("")
        print("{}: {} passes, {} tables -> Shaders\\mpv\\{}".format(name, len(passes), len(texture_rows), stem))

    table.append("// The files behind the resources, from the repository root, for the harness.")
    table.append("#ifdef MPV_SHADER_FILES")
    table.append("static const struct { UINT resid; const wchar_t* path; } kMpvShaderFiles[] = {")
    table += ["\t{{ {}, L\"{}\" }},".format(r, path) for r, path in files]
    table.append("};")
    table.append("#endif")

    tables_path = os.path.join(ROOT, "Source", "Upscale", "MpvShaderTables.h")
    os.makedirs(os.path.dirname(tables_path), exist_ok=True)
    open(tables_path, "w", encoding="utf-8", newline="\n").write("\n".join(table) + "\n")

    while cmd and cmd[-1] == "":
        cmd.pop()
    replace_block(os.path.join(ROOT, "Shaders", "compile_shaders.cmd"), CMD_BEGIN, CMD_END, cmd, "\nEXIT /B\n\n:SubColorText")
    replace_block(os.path.join(ROOT, "Source", "res", "MpcVideoRenderer.rc2"), RC_BEGIN, RC_END, rc,
                  "//IDF_PS_11_TEST")
    print("{} resources from {} to {}; tables in {}".format(resid - FIRST_RESOURCE_ID, FIRST_RESOURCE_ID, resid - 1,
                                                            os.path.relpath(tables_path, ROOT)))


def main():
    args = sys.argv[1:]
    tools = os.path.join(ROOT, "tools", "dlssnr_probe", "upscalers", "tools")
    upstream = os.path.join(ROOT, "tools", "dlssnr_probe", "upscalers")
    for flag in ("--tools", "--upstream"):
        if flag in args:
            i = args.index(flag)
            if flag == "--tools":
                tools = args[i + 1]
            else:
                upstream = args[i + 1]
            del args[i:i + 2]
    if args == ["renderer"]:
        renderer(upstream, tools)
        return 0
    if len(args) != 2:
        print(__doc__)
        return 2
    translate(args[0], args[1], tools)
    return 0


if __name__ == "__main__":
    sys.exit(main())
